export const colorToEmoji: Record<string, string> = {
  RED: '🔴',
  GREEN: '🟢',
  BLUE: '🔵',
  YELLOW: '🟡',
  PURPLE: '🟣',
  PINK: '💗',
  ORANGE: '🟠',
  GRAY: '⚫',
  WHITE: '⚪',
  CYAN: '🔷',
  LIME: '💚',
  BROWN: '🟤',
  TEAL: '🔹',
  INDIGO: '🔸',
  VIOLET: '🔺',
  BLACK: '⚫',
  MAGENTA: '💜',
  AQUA: '💠',
  LAVENDER: '💜',
  MAROON: '🟤',
  OLIVE: '🟢',
  NAVY: '🔵',
  CRIMSON: '🔴',
  GOLD: '🟡',
  SILVER: '⚪',
  TURQUOISE: '🔷',
  CORAL: '🔸',
  TOMATO: '🔴',
  CHOCOLATE: '🟤',
  SLATE: '⚫',
  STEEL: '⚪',
  PLUM: '🟣',
  SALMON: '🔸',
  PERIWINKLE: '🔷',
  MINT: '💚',
  LEMON: '🟡',
  PEACH: '🔸',
  ROSE: '💗',
  LILAC: '💜',
  AUBURN: '🟤',
  CERULEAN: '🔵',
  VERMILION: '🔴',
  AQUAMARINE: '💠',
  BURGUNDY: '🟤',
  COBALT: '🔵',
  EMERALD: '💚',
  GARNET: '🔴',
  JADE: '💚',
  JASPER: '🟤',
  LAPIS: '🔵',
  MAUVE: '💜',
  OCHRE: '🟡',
  RUBY: '🔴',
  SAPPHIRE: '🔵',
  SCARLET: '🔴',
  TAN: '🟤',
  TAUPE: '⚫',
  TOPAZ: '💠',
  ULTRAMARINE: '🔵',
  VERDIGRIS: '💚',
  VIRIDIAN: '💚',
  WHEAT: '🟡',
  ZINC: '⚪',
  ZIRCON: '💠',
};

export function getColorEmoji(color: string): string {
  return colorToEmoji[color.toUpperCase()] || '⚪'; // Added toUpperCase for robustness
}

// Function to get a random hex color code for Mattermost attachments
export function getRandomColor(): string {
  const colors = ["#FF5733", "#33FF57", "#3357FF", "#FF33A1", "#F1C40F", "#9B59B6", "#1ABC9C", "#E74C3C", "#3498DB", "#2ECC71"];
  return colors[Math.floor(Math.random() * colors.length)];
}
